apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-expire-partitions
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.expired | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "dataset-controller.fullname" . }}; do echo waiting for {{ include "dataset-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X DELETE http://{{ include "dataset-controller.fullname" . }}/datasets/partitions/expired
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-delete-raw-partn-post-compaction
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.raw_version_compacted | quote  }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "dataset-controller.fullname" . }}; do echo waiting for {{ include "dataset-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X DELETE http://{{ include "dataset-controller.fullname" . }}/datasets/partitions/raw-version-of-compacted
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-detect-partitions
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.detect  | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "dataset-controller.fullname" . }}; do echo waiting for {{ include "dataset-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "dataset-controller.fullname" . }}/datasets/partitions/detect
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-compute-partitions-size
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.refresh_size | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "dataset-controller.fullname" . }}; do echo waiting for {{ include "dataset-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "dataset-controller.fullname" . }}/datasets/partitions/refresh-size
          restartPolicy: Never

---

{{ if (eq (index .Values "billing-service" "enabled") true) }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-apm-billing
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.billing | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "dataset-controller.fullname" . }}; do echo waiting for {{ include "dataset-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "dataset-controller.fullname" . }}/datasets/profile/billing
          restartPolicy: Never
{{ end }}
