{{- if .Values.apmConnectAutoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Namespace }}-apm-connect
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "autoscaling.apmConnectAutoscaling.fullname" . }}
  minReplicas: {{ .Values.apmConnectAutoscaling.minReplicas }}
  maxReplicas: {{ template "autoscaling.apmConnectAutoscaling.maxReplicas" . }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: es_connect_heap_utilization_pcnt
      target: 
        type: AverageValue
        averageValue: {{ .Values.apmConnectAutoscaling.memory.targetPCNT }}
  - type: Pods
    pods:
      metric:
        name: es_connect_nio_utilization_pcnt
      target:
        type: AverageValue
        averageValue: {{ .Values.apmConnectAutoscaling.memory.targetPCNT }}
  - type: Pods
    pods:
      metric:
        name: kafka_server_fetch_byte_rate
      target:
        type: AverageValue
        averageValue: 100
  - type: Resource
    resource:
      name: cpu
      target: 
        type: AverageValue
        averageValue: {{ .Values.apmConnectAutoscaling.cpu.targetAverageValue }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
      selectPolicy: Max
{{- end -}}
