apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-sftrace
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: sftrace
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
      jaeger:
        http:
          enabled: true
          host: 0.0.0.0:14268
    queue:
      mem:
        events: 8192
    output.kafkarest:
      enabled: true
      hosts: ["{{ .Values.sftrace.output.host }}:{{ .Values.sftrace.output.port }}"]
      topic: beats
      token: "{{ .Values.sftrace.output.token }}"
      bulk_max_size: 1024
      worker: 8
    setup.template.enabled: false
    logging.metrics.enabled: true
    logging.to_stderr: true
    logging.json: true

