{{- if .Values.suspectedClientBlocker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- if .Values.controller.configAnnotations }}
  annotations: {{ toYaml .Values.controller.configAnnotations | nindent 4 }}
{{- end }}
  name: {{ include "nginx-ingress.fullname" . }}-suspected-client-block
data:
  config.yaml: |+
    ---
    period: {{ .Values.suspectedClientBlocker.config.interval }}
    interval: {{ .Values.suspectedClientBlocker.config.failedRequestThresholdPerClient }}
    minRequestInConsiderationPerClient: {{ .Values.suspectedClientBlocker.config.minRequestInConsiderationPerClient }}
    logFilePath: "{{ .Values.suspectedClientBlocker.config.logFilePath }}"
    {{- if .Values.suspectedClientBlocker.whiteListIPs }}
    whiteListIPs: {{ toYaml .Values.suspectedClientBlocker.config.whiteListIPs | nindent 4 }}
    {{- end }}
{{- end }}
