# Default values for Ingest Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: snappyflowml/signatures
  tag: 6
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  servicePort: 8888

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  signatures:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi

