global:
  ingress:
    enabled: false

  postgresql:
    host: ""
    postgresqlDatabase: archival
    postgresqlUsername: archive
    postgresqlPassword: archive123
    servicePort: 5432

  # Below parameter needs to use the PLAIN_TEXT port
  kafkaBrokers: "localhost:9092,localhost1:9092"

  # Certain components which use SASL_PLAIN will use this port along with above machines
  kafkaSASLPort: "9093"

  secrets:
    gcs:
      enable: false
    aws:
      enable: true

  archival:
    enabled: true
    releaseName: archival

  sfAgentInput:
    host: 127.0.0.1
    port: 443
    scheme: https

  maxTasksPerTopic: 5

  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: "snappyflow-app"
  snappyflowAppName: "sf-datapath"

  imagePullSecrets:
  - name: xxxx

creds: "control:$apr1$pjbvxsh8$UnVE6PZ/3874l.cJ.Xc1e0"

# Pod priority class value
priority: 100

autoscaling:
  archivalConnectAutoscaling:
    minReplicas: 2
    maxReplicas: 5

  apmConnectAutoscaling:
    minReplicas: 2
    maxReplicas: 5

  restKafkaAutoscaling:
    minReplicas: 2
    maxReplicas: 5

  minioAutoscaling:
    minReplicas: 2
    maxReplicas: 5

sfk-interface:
  schedules:
    sink: "*/15 * * * *"
