# Default values for Ingest Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: snappyflowml/authenticator
  tag: 7
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serverPort: ":5006"

admin:
  profileKey: admin
  userName: admin
  password: admin

signingKey: "mysecretkey"

service:
  servicePort: 5006

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  authenticator:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 50Mi
