apiVersion: v1
kind: Service
metadata:
  name: {{ include "signatures-and-kafka-apis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "signatures-and-kafka-apis.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.service.servicePort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "signatures-and-kafka-apis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}